// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Chcjihb-QCcinbVOqyAGQ_mncqiYSx4',
    appId: '1:151926947380:web:04278de2e8a3aa744cd461',
    messagingSenderId: '151926947380',
    projectId: 'dummy-71a3a',
    authDomain: 'dummy-71a3a.firebaseapp.com',
    storageBucket: 'dummy-71a3a.firebasestorage.app',
    measurementId: 'G-M11MQN9M7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDU6V2GppDFw6O6lGD5DWKE6wq3Y7K5DA',
    appId: '1:151926947380:android:d7245e1b6daf28cc4cd461',
    messagingSenderId: '151926947380',
    projectId: 'dummy-71a3a',
    storageBucket: 'dummy-71a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPJM4D0dl_YqGcAI6Yb9rsupOx8PZ_N4',
    appId: '1:151926947380:ios:59a55ac440964cb64cd461',
    messagingSenderId: '151926947380',
    projectId: 'dummy-71a3a',
    storageBucket: 'dummy-71a3a.firebasestorage.app',
    iosBundleId: 'com.example.medrphaLabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUPJM4D0dl_YqGcAI6Yb9rsupOx8PZ_N4',
    appId: '1:151926947380:ios:59a55ac440964cb64cd461',
    messagingSenderId: '151926947380',
    projectId: 'dummy-71a3a',
    storageBucket: 'dummy-71a3a.firebasestorage.app',
    iosBundleId: 'com.example.medrphaLabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Chcjihb-QCcinbVOqyAGQ_mncqiYSx4',
    appId: '1:151926947380:web:f2b1ef32025443344cd461',
    messagingSenderId: '151926947380',
    projectId: 'dummy-71a3a',
    authDomain: 'dummy-71a3a.firebaseapp.com',
    storageBucket: 'dummy-71a3a.firebasestorage.app',
    measurementId: 'G-83BTJ932KQ',
  );

}